controller_manager:
  ros__parameters:
    use_sim_time: true  
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    # Your wheel joint names
    left_wheel_names:  ["fl_wheel_joint", "rl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "rr_wheel_joint"]

    # Match your URDF geometry
    wheel_separation: 0.33     # y: +0.165 to -0.165  => 0.33 m
    wheel_radius: 0.06

    # Frames & runtime
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: true

    # Optional niceties
    open_loop: false
    velocity_rolling_window_size: 10