<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="skid_steer_bot">
  <!-- Params -->
  <xacro:property name="base_l" value="0.50"/>   <!-- base length (m) -->
  <xacro:property name="base_w" value="0.30"/>   <!-- base width (m)  -->
  <xacro:property name="base_h" value="0.12"/>
  <xacro:property name="wheel_r" value="0.06"/>
  <xacro:property name="wheel_w" value="0.03"/>

  <!-- Base link -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="8.0"/>
      <inertia ixx="0.15" iyy="0.20" izz="0.25" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${wheel_r + base_h/2}" rpy="0 0 0"/>
      <geometry><box size="${base_l} ${base_w} ${base_h}"/></geometry>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_r + base_h/2}" rpy="0 0 0"/>
      <geometry><box size="${base_l} ${base_w} ${base_h}"/></geometry>
    </collision>
  </link>

    <!-- LiDAR mast -->
  <link name="lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${wheel_r + base_h + 0.05}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.02" length="0.10"/></geometry>
      <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_r + base_h + 0.05}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.02" length="0.10"/></geometry>
    </collision>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <!-- mount on top of the chassis -->
    <origin xyz="0 0 ${wheel_r + base_h/2 + 0.05}" rpy="0 0 0"/>
  </joint>


<gazebo reference="lidar_link">
  <sensor name="lidar" type="lidar">
    <always_on>true</always_on>
    <update_rate>10</update_rate>
    <visualize>true</visualize>
    <topic>scan</topic>
    <gz_frame_id>lidar_link</gz_frame_id>
    <ray>
      <scan>
        <horizontal>
          <samples>720</samples>
          <resolution>1</resolution>
          <min_angle>-1.5708</min_angle>   <!-- -90 deg -->
          <max_angle> 1.5708</max_angle>   <!-- +90 deg -->
        </horizontal>
      </scan>
      <range>
        <min>0.12</min>
        <max>10.0</max>
        <resolution>0.01</resolution>
      </range>
      <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.01</stddev>
      </noise>
    </ray>
  </sensor>
</gazebo>


  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_r}" length="${wheel_w}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_r}" length="${wheel_w}"/></geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} 0.03" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>


  <!-- 4 wheels (FL, RL, FR, RR). Note left is +y, right is -y -->
  <xacro:wheel name="fl_wheel" x="${0.20}" y="${0.165}" />
  <xacro:wheel name="rl_wheel" x="${-0.2}" y="${0.165}" />
  <xacro:wheel name="fr_wheel" x="${0.20}" y="${-0.165}" />
  <xacro:wheel name="rr_wheel" x="${-0.2}" y="${-0.165}" />

  <gazebo reference="fl_wheel">
  <mu>1.5</mu>
  <mu2>1.5</mu2>
  <kp>1000000.0</kp>
  <kd>1000.0</kd>
  <minDepth>0.001</minDepth>
  <maxVel>0.2</maxVel>
  <slip1>0.0</slip1>
  <slip2>0.0</slip2>
</gazebo>
<gazebo reference="fr_wheel">
  <mu>1.5</mu><mu2>1.5</mu2><kp>1000000.0</kp><kd>1000.0</kd>
  <minDepth>0.001</minDepth><maxVel>0.2</maxVel><slip1>0.0</slip1><slip2>0.0</slip2>
</gazebo>
<gazebo reference="rl_wheel">
  <mu>1.5</mu><mu2>1.5</mu2><kp>1000000.0</kp><kd>1000.0</kd>
  <minDepth>0.001</minDepth><maxVel>0.2</maxVel><slip1>0.0</slip1><slip2>0.0</slip2>
</gazebo>
<gazebo reference="rr_wheel">
  <mu>1.5</mu><mu2>1.5</mu2><kp>1000000.0</kp><kd>1000.0</kd>
  <minDepth>0.001</minDepth><maxVel>0.2</maxVel><slip1>0.0</slip1><slip2>0.0</slip2>
</gazebo>

  <!-- 2D LiDAR (GPU-based) publishing a planar scan -->


  
  <!-- ros2_control: diff drive using left and right wheel pairs -->
  <ros2_control name="GazeboSimSystem" type="system">
  <hardware>
    <plugin>gz_ros2_control/GazeboSimSystem</plugin>
  </hardware>

  <!-- wheel joints with interfaces -->
  <joint name="fl_wheel_joint">
    <command_interface name="velocity"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
  <joint name="rl_wheel_joint">
    <command_interface name="velocity"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
  <joint name="fr_wheel_joint">
    <command_interface name="velocity"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
  <joint name="rr_wheel_joint">
    <command_interface name="velocity"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
</ros2_control>

<gazebo>
  <plugin filename="libgz_ros2_control-system.so"
          name="gz_ros2_control::GazeboSimROS2ControlPlugin">
    <controller_manager_prefix_node_name>controller_manager</controller_manager_prefix_node_name>
    <parameters>/home/tersoo/autonomous-robot-logging-with-ROS2-jazzy/ros2_ws/src/robot_logging/config/controllers.yaml</parameters>
  </plugin>
</gazebo>



</robot>
